[package]
name = "nionx01/frameworkplus"
version = "0.0.1"
description = "A security-first framework for protecting, validating, and managing Roblox systems"
license = "MPL-2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = [
    "src",
    "src/**",
    "LICENSE",
]

[dependencies]